channels:
- conda-forge
- defaults
dependencies:
- python=3.12.10
- numpy=2.2.6
- pandas=2.2.3
- plotly=6.1.1
- pillow=11.2.1
- psycopg2==2.9.10
- werkzeug=3.1.3
- markupsafe=3.0.2
- jinja2=3.1.6
- click=8.2.1
- itsdangerous=2.2.0
- colorama=0.4.6
- pytz=2025.2
- pip:
  - flask==2.3.3
  - flask-cors==4.0.0
  - flask-sqlalchemy==3.1.1
  - sqlalchemy==2.0.23
  - gpxpy==1.5.0
  - geopy==2.4.0
  - geographiclib==2.0
  - googlemaps==4.10.0
  - google-auth==2.23.4
  - google-auth-oauthlib==1.1.0
  - oauthlib==3.2.2
  - requests-oauthlib==2.0.0
  - pyasn1==0.6.1
  - pyasn1-modules==0.4.2
  - rsa==4.9.1
  - requests==2.31.0
  - python-dotenv==1.0.0
  - python-dateutil==2.8.2
  - urllib3==2.4.0
  - certifi==2025.4.26
  - charset-normalizer==3.4.2
  - idna==3.10
  - pytest==7.4.3
  - black==23.9.1
  - flake8==6.1.0
  - pycodestyle==2.11.1
  - pyflakes==3.1.0
  - mccabe==0.7.0
  - mypy-extensions==1.1.0
  - pathspec==0.12.1
  - platformdirs==4.3.8
  - pluggy==1.6.0
  - iniconfig==2.1.0
  - kaleido==0.2.1
  - tenacity==9.1.2
  - greenlet==3.2.2
  - typing-extensions==4.13.2
  - cachetools==5.5.2
  - blinker==1.9.0
name: gps_tracking
